# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: origin
      url-base: ssh://git@git.riedo.com:10022
  #
  # Please add items below based on alphabetical order
  projects:
    - name: ci-tools
      revision: e01f3bce2a94847253369efb9a081f5c0e9ec882
      path: tools/ci-tools
    - name: civetweb
      revision: 99129c5efc907ea613c4b73ccff07581feb58a7a
      path: modules/lib/civetweb
    - name: fatfs
      revision: df96914dd989907f3a5de4cb95b116c2f305820d
      path: modules/fs/fatfs
    - name: lvgl
      revision: d4708d0a432e95f51bdc712591ba5295b751140c
      path: modules/lib/gui/lvgl
    - name: mbedtls
      revision: bbcb1b14285ac1b694d8c7e47c2f139c80b7fc4c
      path: modules/crypto/mbedtls
    - name: mcumgr
      revision: 84934959d2d1722a23b7e7e200191ae4a6f96168
      path: modules/lib/mcumgr
    - name: net-tools
      revision: 30b7efa827b04d2e47840716b0372737fe7d6c92
      path: tools/net-tools
    - name: nffs
      revision: bc62a2fa9d98ddb5d633c932ea199bc68e10f194
      path: modules/fs/nffs
    - name: oss/hal_nxp
      revision: 016c5b1beae35a1ee177893ba41c05c8b1846047
      path: modules/hal/nxp
      remote: origin
    - name: open-amp
      revision: 9b591b289e1f37339bd038b5a1f0e6c8ad39c63a
      path: modules/lib/open-amp
    - name: openthread
      revision: 3c32244f098f8daf8741efe0a2ad839b67f8567f
      path: modules/lib/openthread
    - name: segger
      revision: 6fcf61606d6012d2c44129edc033f59331e268bc
      path: modules/debug/segger
    - name: tinycbor
      path: modules/lib/tinycbor
      revision: 6966f6140cb870b792330a5186020eb1f4151f3e
    - name: littlefs
      path: modules/fs/littlefs
      revision: fe9572dd5a9fcf93a249daa4233012692bd2881d

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
